// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function SearchInput(arg1) {
  return window['go']['main']['SearchEngine']['SearchInput'](arg1);
}
